services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app                # Mount project folder
      - /app/node_modules     # Keep node_modules inside container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  
      - CHOKIDAR_INTERVAL=100
      - WATCHPACK_POLLING=true
    command: npm run dev 
    restart: always
